[package]
name = "joinccmd"
version = "0.1.0"
edition = "2021"
authors = ["vmc <vmc.coding@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
chrono = "0.4.31"
clap = { version = "4.3.12", features = ["derive"] }
libjoinc = { path = "../libjoinc" }
